[package]
name = "dot32_intro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
# bevy = { version = "0.7.0", features = ["dynamic"] }